- hosts: vagrants
  sudo: true
  user: vagrant
  vars:
    vagrant_home: "/home/vagrant"
    python_version: 2.7.10
  tasks:
    - name: pythonビルド用パッケージのインストール
      apt: name={{ item }} update_cache=yes
      with_items:
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm

    - name: gitのインストール
      apt: name=git update_cache=yes

    - name: pyenvのインストール
      git: repo=https://github.com/yyuu/pyenv.git
           dest={{ vagrant_home }}/.pyenv
           version=master
      sudo: no

    - name: pyenvのパスを設定する
      shell: |
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> "{{ vagrant_home }}/.bash_profile"
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> "{{ vagrant_home }}/.bash_profile"
        echo 'eval "$(pyenv init -)"' >> "{{ vagrant_home }}/.bash_profile"
      sudo: no

    - name: pythonのインストール
      shell: |
        bash -lc "pyenv install {{ python_version }}"
        bash -lc "pyenv rehash"
      sudo: no

    - name: pythonのグローバルバージョンを設定
      shell: bash -lc "pyenv global {{ python_version }}"
      sudo: no    

    - name: pepper SDKの解凍
      shell: tar zxvf pynaoqi-python2.7-2.3.1.25-linux64.tar.gz chdir=data
      sudo: no

    - name: pepper SDK にパスを通す
      shell: |
        echo 'export PYTHONPATH="$PYTHONPATH:~/data/pynaoqi-python2.7-2.0.5.3-linux64"' >> "{{ vagrant_home }}/.bash_profile"
        echo 'export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:~/data/pynaoqi-python2.7-2.0.5.3-linux64"' >> "{{ vagrant_home }}/.bash_profile"
      sudo: no
