- hosts: vagrants
  sudo: true
  user: vagrant
  vars:
    vagrant_home: "/home/vagrant"
  tasks:
    - name: pipのインストール
      apt: name=python-pip update_cache=yes

    - name: pepper SDKの解凍
      shell: |
        tar zxvf pynaoqi-python2.7-2.3.1.25-linux64.tar.gz
        rm -f pynaoqi-python2.7-2.3.1.25-linux64.tar.gz
        chdir=data
      sudo: no

    - name: pepper SDK にパスを通す
      shell: |
        echo 'export PYTHONPATH="$PYTHONPATH:$HOME/data/pynaoqi-python2.7-2.3.1.25-linux64"' >> "{{ vagrant_home }}/.bash_profile"
        echo 'export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$HOME/data/pynaoqi-python2.7-2.3.1.25-linux64"' >> "{{ vagrant_home }}/.bash_profile"
      sudo: no

    - name: 日本語入力を有効化
      shell: locale-gen ja_JP.UTF-8

    - name: localeの設定
      shell: bash -lc 'LC_ALL="en_US.UTF-8"'
      sudo: no
