- hosts: vagrants
  sudo: true
  user: vagrant
  tasks:
    - name: install build-essential
      apt: name=build-essential update_cache=yes

    - name: install git
      apt: name=git

    - name: install python-pip
      apt: name=python-pip

    - name: virtual env
      pip: name=virtualenv
